"""events table

Revision ID: 314039145b57
Revises: a2f61fcdb399
Create Date: 2026-08-27 20:32:21.892264

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "314039145b57"
down_revision: str | Sequence[str] | None = "a2f61fcdb399"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("release_id", sa.String(), nullable=False),
        sa.Column("campaign_id", sa.String(), nullable=True),
        sa.Column("trace_id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("artifact_digests", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("environment_digest", sa.String(), nullable=False),
        sa.Column("cost", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_classification", sa.String(), nullable=False),
        sa.Column("payload_uri", sa.String(), nullable=True),
        sa.Column("payload_digest", sa.String(), nullable=True),
        sa.Column("chain_seq", sa.BigInteger(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "chain_seq", name="uq_events_tenant_chain_seq"),
    )
    op.create_index(op.f("ix_events_event_hash"), "events", ["event_hash"], unique=True)
    op.create_index(op.f("ix_events_event_id"), "events", ["event_id"], unique=True)
    op.create_index(op.f("ix_events_tenant_id"), "events", ["tenant_id"], unique=False)
    op.create_index(
        "ix_events_tenant_occurred_at", "events", ["tenant_id", "occurred_at"], unique=False
    )
    op.create_index(op.f("ix_events_trace_id"), "events", ["trace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_trace_id"), table_name="events")
    op.drop_index("ix_events_tenant_occurred_at", table_name="events")
    op.drop_index(op.f("ix_events_tenant_id"), table_name="events")
    op.drop_index(op.f("ix_events_event_id"), table_name="events")
    op.drop_index(op.f("ix_events_event_hash"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
