"""The selection plane (deliverable E4): trusted selector, promotion policy,
authority tiers, recursive-claim gate, and the release pointer's CAS
authority (PRD §12.5, §12.6, §13.3, FR-011)."""

from __future__ import annotations

from evoruntime.selection.authority import (
    PHASE_1_MAX_TIER,
    AuthorityTier,
    ResolvedRelease,
    assert_phase1_admissible,
    resolve_authority_tier,
)
from evoruntime.selection.errors import (
    AlreadyFrozenError,
    CasConflictError,
    InvalidPromotionPolicyError,
    NominationRuleError,
    PointerAuditError,
    RecursiveClaimDeniedError,
    SelectionError,
    TierRejectedError,
)
from evoruntime.selection.nomination import (
    NOMINATE_EVENT_KIND,
    REJECT_EVENT_KIND,
    FrozenNominees,
    InMemoryNominationLedger,
    NominationEvent,
    NominationLedger,
    NominationRule,
    RegistryNominationLedger,
    SelectionObservation,
    TrustedSelector,
)
from evoruntime.selection.policy import (
    CONDITION_BUDGET,
    CONDITION_NO_CRITICAL_FAILURE,
    CONDITION_NO_INTEGRITY_FINDINGS,
    CONDITION_PROTECTED_SLICES,
    CONDITION_STATISTICAL,
    CONDITION_TRANSFER_SCOPE,
    ConditionResult,
    PairedScores,
    PromotionDecision,
    PromotionEvidence,
    PromotionPolicyDocument,
    evaluate_promotion,
)
from evoruntime.selection.recursive_gate import (
    ARTIFACT_OPTIMIZATION_LABEL,
    RECURSIVE_CLAIM_ENABLED,
    RECURSIVE_IMPROVEMENT_LABEL,
    RecursiveClaimCondition,
    RecursiveClaimEvidence,
    RecursiveClaimVerdict,
    assert_label_allowed,
    claim_label,
    evaluate_recursive_claim,
)
from evoruntime.selection.release_pointer import (
    InMemoryPointerAuditLog,
    PointerAuditEntry,
    PointerAuditLog,
    ReleasePointer,
    ReleasePointerStore,
)

__all__ = [
    "ARTIFACT_OPTIMIZATION_LABEL",
    "CONDITION_BUDGET",
    "CONDITION_NO_CRITICAL_FAILURE",
    "CONDITION_NO_INTEGRITY_FINDINGS",
    "CONDITION_PROTECTED_SLICES",
    "CONDITION_STATISTICAL",
    "CONDITION_TRANSFER_SCOPE",
    "NOMINATE_EVENT_KIND",
    "PHASE_1_MAX_TIER",
    "RECURSIVE_CLAIM_ENABLED",
    "RECURSIVE_IMPROVEMENT_LABEL",
    "REJECT_EVENT_KIND",
    "AlreadyFrozenError",
    "AuthorityTier",
    "CasConflictError",
    "ConditionResult",
    "FrozenNominees",
    "InMemoryNominationLedger",
    "InMemoryPointerAuditLog",
    "InvalidPromotionPolicyError",
    "NominationEvent",
    "NominationLedger",
    "NominationRule",
    "NominationRuleError",
    "PointerAuditEntry",
    "PointerAuditError",
    "PointerAuditLog",
    "PairedScores",
    "PromotionDecision",
    "PromotionEvidence",
    "PromotionPolicyDocument",
    "RecursiveClaimCondition",
    "RecursiveClaimDeniedError",
    "RecursiveClaimEvidence",
    "RecursiveClaimVerdict",
    "RegistryNominationLedger",
    "ReleasePointer",
    "ReleasePointerStore",
    "ResolvedRelease",
    "SelectionError",
    "SelectionObservation",
    "TierRejectedError",
    "TrustedSelector",
    "assert_label_allowed",
    "assert_phase1_admissible",
    "claim_label",
    "evaluate_promotion",
    "evaluate_recursive_claim",
    "resolve_authority_tier",
]
